In [1]:
from qiskit import QuantumRegister, ClassicalRegister, QuantumCircuit, Aer
from numpy import pi

In [6]:
qreg_q = QuantumRegister(2, 'q')
creg_c = ClassicalRegister(2, 'c')
circuit = QuantumCircuit(qreg_q, creg_c)

circuit.cx(qreg_q[0], qreg_q[1])
circuit.y(qreg_q[1])
circuit.cx(qreg_q[0], qreg_q[1])

In [7]:
circuit.draw()

q_0: ──■─────────■──
     ┌─┴─┐┌───┐┌─┴─┐
q_1: ┤ X ├┤ Y ├┤ X ├
     └───┘└───┘└───┘
c: 2/═══════════════

In [8]:
# Run the quantum circuit on a statevector simulator backend
backend = Aer.get_backend('statevector_simulator')

In [9]:
# Create a Quantum Program for execution
job = backend.run(circuit)
result = job.result()
outputstate = result.get_statevector(circuit, decimals=3)
print(outputstate)

[0.-0.j 0.+0.j 0.+1.j 0.-0.j]


In [11]:
qreg_q2 = QuantumRegister(2, 'q')
creg_c2 = ClassicalRegister(2, 'c')
circuit2 = QuantumCircuit(qreg_q2, creg_c2)

circuit2.y(qreg_q2[0])
circuit2.y(qreg_q2[1])
circuit2.draw()

┌───┐
q_0: ┤ Y ├
     ├───┤
q_1: ┤ Y ├
     └───┘
c: 2/═════

In [12]:
# Run the quantum circuit on a statevector simulator backend
backend2 = Aer.get_backend('statevector_simulator')

In [13]:
# Create a Quantum Program for execution
job2 = backend2.run(circuit2)
result2 = job2.result()
outputstate2 = result2.get_statevector(circuit2, decimals=3)
print(outputstate2)

[-0.+0.j  0.-0.j  0.+0.j -1.+0.j]


optin-d

In [14]:
qreg_q3 = QuantumRegister(2, 'q')
creg_c3 = ClassicalRegister(2, 'c')
circuit3 = QuantumCircuit(qreg_q3, creg_c3)

circuit3.y(qreg_q3[1])
circuit3.z(qreg_q3[0])
circuit3.draw() 

┌───┐
q_0: ┤ Z ├
     ├───┤
q_1: ┤ Y ├
     └───┘
c: 2/═════

In [15]:
# Run the quantum circuit on a statevector simulator backend
backend3 = Aer.get_backend('statevector_simulator')

In [16]:
# Create a Quantum Program for execution
job3 = backend3.run(circuit3)
result3 = job3.result()
outputstate3 = result3.get_statevector(circuit3, decimals=3)
print(outputstate3)

[ 0.-0.j  0.+0.j  0.+1.j -0.+0.j]


In [19]:
outputstate

array([0.-0.j, 0.+0.j, 0.+1.j, 0.-0.j])

In [20]:
outputstate2

array([-0.+0.j,  0.-0.j,  0.+0.j, -1.+0.j])

In [21]:
outputstate3

array([ 0.-0.j,  0.+0.j,  0.+1.j, -0.+0.j])